//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServiceTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlServiceTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Name&quot;:&quot;id&quot;,&quot;SqlDataType&quot;:{&quot;SqlDbType&quot;:8,&quot;MaxLength&quot;:4,&quot;Precision&quot;:10,&quot;Scale&quot;:0,&quot;Collation&quot;:null},&quot;Position&quot;:0,&quot;PkPosition&quot;:1,&quot;IsNullable&quot;:false,&quot;IsIdentity&quot;:true,&quot;IdentitySeed&quot;:1,&quot;IdentityIncrement&quot;:1,&quot;IsComputed&quot;:false,&quot;IsPersisted&quot;:false,&quot;ComputedLogic&quot;:null,&quot;HasDefault&quot;:false,&quot;DefaultLogic&quot;:null},{&quot;Name&quot;:&quot;rank&quot;,&quot;SqlDataType&quot;:{&quot;SqlDbType&quot;:8,&quot;MaxLength&quot;:4,&quot;Precision&quot;:10,&quot;Scale&quot;:0,&quot;Collation&quot;:null},&quot;Position&quot;:1,&quot;PkPosition&quot;:null,&quot;IsNullable&quot;:true,&quot;IsIdentity&quot;:false,&quot;IdentitySeed&quot;:null,&quot;IdentityIncrement&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestTable01_Schema {
            get {
                return ResourceManager.GetString("TestTable01_Schema", resourceCulture);
            }
        }
    }
}
